{
    "name": "throw_in_configure",
    "description": "throws an exception in the computation configure function",
    "computations": {
        "(client)": {
            "messages": {
                "testcomp": "*"
            }
        }, 
        "testcomp": {
            "dso": "libarras4_testcomputation.so", 
            "entry": "yes", 
            "forward":true,
            "errorInStart":"throw",
            "requirements": {
                "computationAPI": "4.x",
                "packaging_system": "current-environment",
                "resources": {
                    "cores": 1.0,
                    "memoryMB": 16384
                }
            },
            "messages": {
                "(client)": "*" 
            }
        }
    }
}
